language: ruby
rvm:
  - 2.3.0
before_script:
  - gem install rails --no-ri --no-rdoc
  - cd ..
  - printf 'n\ny\ny\nn' | rails new interactive_app -m smashing-template/template.rb -B
  - cd interactive_app/
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - cp ../smashing-template/test/example_spec.rb spec/example_spec.rb
  - cp ../smashing-template/test/example.feature features/example.feature
  - cp ../smashing-template/test/example_steps.rb features/example_steps.rb
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec rake cucumber
  - bundle exec rubocop ../smashing-template/
